### ISSUE TITLE
does not work with PuppeteerSharp 3.0.0 

### ISSUE THREAD

**Issue by juergenr** [hlaueriksson/puppeteer-sharp-contrib#11]
e.g. ElementHandle eh = await page.QuerySelectorWithContentAsync("div> span", "Next");
results in:

error CS0012: The type 'ElementHandle' is defined in an assembly that is not referenced. You must add a reference to assembly 'PuppeteerSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

I had worked before updating PuppeteerSharp to version 3.0.0 
Testet in .Net Framework 4.8

**Comment by hlaueriksson** [comment]
@juergenr Thanks for reporting this issue!

I bumped the dependency in version [4.0.0](https://www.nuget.org/packages/PuppeteerSharp.Contrib.Extensions/4.0.0) of `PuppeteerSharp.Contrib.Extensions`. I hope this works for you.

You should probably also be able to use the just released version [4.0.0](https://www.nuget.org/packages/PuppeteerSharp/4.0.0) of `PuppeteerSharp`. Check out the [sample projects](https://github.com/hlaueriksson/puppeteer-sharp-contrib/tree/master/samples) for this, even though I also bumped the target framework to `net5.0`.

**Comment by juergenr** [comment]
Hi @hlaueriksson,
thanks for updating! I tested with PuppeteerSharp 4.0.0 and it seems to work.
Thanks again for your fast support.
